class InviteError(Exception):
    pass


class LoginError(Exception):
    pass
